CSCfi/exam

public/app/reservation/reservation_details.html

- template got broken while refactoring

CSCEXAM-3 fix reservation details template to show missing teachers

---

public/app/examination/clock/examinationClock.component.js
public/app/examination/examination.component.js

- no autosave when switching active section
- autosave failed when time ran out
- delay of a few seconds in detecting that exam time ended

CSCEXAM-6 examination autosaver related bugs

---

build.sbt
conf/protractor.conf
project/Karma.scala
project/MockCourseInfo.scala
project/Protractor.scala
project/WebpackServer.scala
protractor/baseConf.js
protractor/ciConf.js
protractor/conf.js
protractor/e2e/teacher-exam-spec.js
protractor/fixtures/Fixture.js
protractor/fixtures/exams.json
protractor/pages/Common.js
protractor/pages/ExamEditor.js
protractor/pages/TeacherDashboard.js

- Added sbt shutdown hooks for webpack and mock processes.

SIT-0000 Fixed protractor tests for webpack.

---

app/frontend/src/app.run.js
app/frontend/src/calendar/calendar.template.html
app/frontend/src/common/historyBack.component.js
app/frontend/src/common/historyBack.template.html
app/frontend/src/enrolment/active/activeEnrolment.template.html
app/frontend/src/enrolment/exams/examEnrolmentDetails.template.html
app/frontend/src/enrolment/finished/examParticipation.template.html
app/frontend/src/exam/editor/creation/courseSelection.template.html
app/frontend/src/exam/editor/creation/newExam.template.html
app/frontend/src/exam/editor/examTabs.component.js
app/frontend/src/exam/editor/examTabs.template.html
app/frontend/src/exam/exam.service.js
app/frontend/src/review/assessment/assessment.template.html
app/frontend/src/review/listing/speedReview.template.html
app/frontend/src/review/questions/assessment/questionAssessment.template.html

- Added reload flag to $location.path() method.

SIT-0000 Created history back component.

---

app/frontend/src/review/assessment/assessment.service.js
app/frontend/src/review/assessment/questions/weightedMultiChoiceAnswer.template.html
app/frontend/src/review/listing/speedReview.component.js
app/frontend/src/utility/paginator/paginator.component.ts
app/views/index.scala.html

- CSCEXAM-5. Fixed
- found some webpack related issues with some img-elements, seems like a bug in URL-loader. Fixed.
- Clearing the selected grade in assessment view produces a JS error when saving. Fixed.
- Paginator component breaks if no pagination items provided. Fixed.

CSCEXAM-5 fix various issues with assessment UI

---

public/app/review/assessment/assessment.service.js
public/app/review/listing/speedReview.component.js

Also noticed that clearing the grade that was given might result in a failure when saving. FIXED in assessment service.

CSCEXAM-5 Fix setting of answer language in speed review component

---

app/frontend/src/navigation/navigation.component.ts
app/frontend/src/session/session.component.ts

- non-student users got a hidden main view because of incorrect
ng-if clause in the template
- make sure that logged in user is set correctly in the navigation
component once login completes successfully

SIT-2018 login related problems fixed

---

app/controllers/ReviewController.java
app/frontend/src/app.filter.ts
app/frontend/src/review/listing/categories/inProgress.component.js
app/frontend/src/review/listing/categories/inProgress.template.html
app/frontend/src/review/listing/reviewList.component.js
app/frontend/src/review/listing/speedReview.component.js
app/frontend/src/review/listing/speedReview.template.html

- needless to download inspections for each review separately. Optimized away.
- fix incorrect calculation in 'diffInMinutes' filter

SIT-0000 fix and optimize issues with review list view

---

app/frontend/src/review/assessment/grading/grading.component.js
app/frontend/src/review/assessment/maturity/grading.component.js

- needs refactoring, there's duplicate code now.
- will be handled in another commit

CSCEXAM-46 fix handling of answer language in maturity assessment

---

app/controllers/ReportController.java
app/controllers/ReviewController.java
app/controllers/iop/ExternalExamController.java
app/models/Exam.java
app/models/ExamParticipation.java
app/system/actors/ExamExpirationActor.java
public/app/review/assessment/general/generalInfo.component.js
public/app/review/assessment/print/printedAssessment.component.js
public/app/review/listing/templates/graded_logged.html

- prefetch all multichoice question options and essay answers
- make exam <-> exam participation a one-to-one relation
- also fix broken finalized assessments paginator in UI

CSCEXAM-49 try to fasten database access in review listing

---

public/app/app.config.js
public/app/enrolment/active/activeEnrolment.template.html
public/app/enrolment/exams/examEnrolmentCandidate.template.html
public/app/enrolment/search/examSearchResult.template.html
public/app/exam/editor/publication/examPublication.template.html

Cherry picked for fix version.

CSCEXAM-70 Fixed enrolment links when course code contains / chars.

---

public/app/exam/editor/publication/examParticipantSelector.template.html
public/app/exam/editor/publication/examPreParticipantSelector.template.html

- in case of a published private exam

CSCEXAM-74 remove removal icons for participants

---

public/app/review/assessment/maturity/grading.template.html

- in assessment view for finalized assessments

CSCEXAM-40 add inspector and examinator names to maturity info

---

app/frontend/package.json
build.sbt

- NpmInstall sbt task typo fix.

CSCEXAM-0000 Fixed fullcalendar type errors.

---

app/frontend/src/maturity/listing/reviewedInspections.template.html
app/frontend/src/maturity/listing/unfinishedInspections.component.js
app/frontend/src/maturity/listing/unfinishedInspections.template.html

CSCEXAM-111 Fixed language inspection listing arrived column sorting.

---

app/backend/controllers/iop/collaboration/CollaborationController.java
app/backend/controllers/iop/collaboration/CollaborativeExamController.java
app/backend/models/json/CollaborativeExam.java
conf/evolutions/default/101.sql

- make use of couch's revisions in exam so that we get some guard against version conflicts when updating documents

CSCEXAM-122 Versioning support for collaborative exams

---

app/backend/controllers/ExamController.java
app/backend/controllers/RoomController.java
app/backend/controllers/SettingsController.java
app/backend/controllers/iop/collaboration/CollaborativeExamController.java
app/backend/controllers/iop/collaboration/CollaborativeExamSectionController.java
app/backend/impl/ExamUpdater.java
app/backend/impl/ExamUpdaterImpl.java
app/backend/models/Exam.java
app/backend/sanitizers/Attrs.java
app/backend/sanitizers/ExamUpdateSanitizer.java
app/backend/util/ConfigUtil.java
app/frontend/src/administrative/settings/settings.template.html
app/frontend/src/assets/languages/locale-en.json
app/frontend/src/assets/languages/locale-fi.json
app/frontend/src/assets/languages/locale-sv.json
app/frontend/src/common/settingsResource.js
app/frontend/src/exam/editor/basic/basicExamInfo.component.ts
app/frontend/src/exam/editor/basic/basicExamInfo.template.html
app/frontend/src/exam/exam.model.ts
app/frontend/src/exam/exam.service.js
conf/application.conf
conf/dev.conf
conf/evolutions/default/103.sql
conf/integrationtest.conf
conf/routes
test/controllers/ExamControllerTest.java

- Only admin can change exam's anonymous setting.

CSCEXAM-147 Added global anonymous review config.

---

app/frontend/src/administrative/statistics/statistics.template.html
app/frontend/src/exam/editor/basic/basicExamInfo.template.html
app/frontend/src/exam/editor/creation/courseSelection.template.html
app/frontend/src/exam/editor/publication/examPublication.template.html
app/frontend/src/exam/editor/sections/section.template.html
app/frontend/src/exam/editor/sections/sectionsList.template.html
app/frontend/src/exam/listing/examList.template.html
app/frontend/src/question/selector/questionSelector.template.html
app/frontend/src/review/assessment/grading/toolbar.template.html
app/frontend/src/review/assessment/maturity/inspectionComments.template.html
app/frontend/src/review/assessment/maturity/toolbar.template.html
app/frontend/src/review/listing/categories/graded.template.html
app/frontend/src/review/listing/categories/gradedLogged.template.html
app/frontend/src/review/listing/dialogs/abortedExams.template.html
app/frontend/src/review/listing/dialogs/noShows.template.html
app/frontend/src/review/listing/reviewList.template.html
app/frontend/src/review/listing/speedReview.template.html

- In angular target='_self' triggers full page refresh and it is slowing things badly.

Removed redundant target='_self' attributes from links.

---

app/frontend/src/assets/languages/locale-en.json

Localization: Anonymous assessment terms

Localization: Anonymous assessment

---

app/backend/controllers/iop/transfer/api/ExternalAttachmentLoader.java
app/backend/controllers/iop/transfer/impl/ExternalAttachmentLoaderImpl.java
app/backend/controllers/iop/transfer/impl/ExternalExamController.java
app/backend/system/SystemInitializer.java
app/backend/system/actors/CollaborativeAssessmentSenderActor.java

- Fixed timeunit bug for CollaborativeAssessmentSenderActor.

Added external attachment handling for assessment sending.

---

app/frontend/src/review/listing/reviewList.component.js

- Should be implemented in ticket CSCEXAM-167.

Collaborative exam add empty array for no-shows.

---

app/backend/controllers/ExamSectionController.java
app/backend/controllers/iop/collaboration/api/CollaborativeAttachmentInterface.java
app/frontend/src/enrolment/finished/collaborativeExamParticipations.component.ts
app/frontend/src/exam/editor/sections/sectionQuestion.component.ts
app/frontend/src/exam/editor/sections/sectionQuestion.template.html
app/frontend/src/question/basequestion/question.component.js
app/frontend/src/question/basequestion/questionBody.component.js
app/frontend/src/question/examquestion/examQuestion.component.js
app/frontend/src/question/question.service.js
app/frontend/src/utility/attachment/attachment.service.ts

CSCEXAM-168 Fixed normal exam question editing.

---

app/frontend/src/dashboard/teacher/categories/examListCategory.component.ts
app/frontend/src/exam/listing/examList.template.html

- Fixed admin style for exam listing with min-height.

CSCEXAM-175 Fixed exam copying.

---

app/backend/controllers/iop/collaboration/impl/CollaborationController.java
app/backend/controllers/iop/collaboration/impl/CollaborativeReviewController.java
app/backend/controllers/iop/collaboration/impl/CollaborativeStudentActionController.java
app/frontend/src/enrolment/finished/examParticipation.component.js

- Feedback information of student assessments was missing from listing view.

CSCEXAM-188 Fixed collaborative exam student feedback.

---

app/frontend/src/assets/languages/locale-fi.json

Changed some Finnish words/terms

CSCEXAM-15 changed words (Finnish)

---

app/backend/controllers/RoomController.java
app/frontend/src/calendar/bookingCalendar.component.ts
app/frontend/src/calendar/calendar.component.ts
app/frontend/src/session/session.service.ts

CSCEXAM-205 fix organisation dropdown behavior

---

app/backend/controllers/ExamController.java
app/backend/controllers/QuestionController.java
app/frontend/src/assets/styles/main.scss
app/frontend/src/question/library/search/librarySearch.component.js
app/frontend/src/question/library/search/librarySearch.template.html

- For admin there is no results until user selects at least one item from dropdown menus.

CSCEXAM-152 Optimized admin question library search.

---

app/backend/controllers/AccessibilityController.java
app/backend/controllers/RoomController.java
app/backend/controllers/iop/transfer/impl/FacilityController.java
app/backend/impl/CalendarHandlerImpl.java
app/backend/models/ExamMachine.java
app/backend/models/ExamRoom.java
app/backend/system/SystemInitializer.java
app/frontend/src/calendar/calendar.component.ts
app/frontend/src/calendar/calendar.service.ts
app/frontend/src/facility/accessibility/accessibilitySelector.component.js

- limit size of payload passed to IOP server by removing data not needed
- rename exam room property accessibility as accessibilities

CSCEXAM-000 facility iop fixes

---

app/backend/controllers/ExamController.java
app/frontend/src/review/assessment/assessment.template.html

-  leave it as null when copying
-  add extra check to assessment template

CSCEXAM-215 language inspection requirement for copied exam

---

app/backend/controllers/ReservationController.java
app/backend/controllers/iop/transfer/impl/ExternalCalendarController.java
app/backend/models/iop/ExternalReservation.java
app/frontend/package-lock.json
app/frontend/package.json
app/frontend/src/enrolment/active/activeEnrolment.template.html
app/frontend/src/reservation/reservation.controller.ts
app/frontend/src/reservation/reservationDetails.template.html
build.sbt
conf/application.conf
conf/evolutions/default/107.sql

- store organisation info within external_reservation relation
- display it on student's dashboard
- display it on reservation management view along with room and machine data for a reservation
- RC-version got bumped in this branch due to problems with testing environments

CSCEXAM-143 organisation info as part of external reservation

---

app/backend/controllers/ExamRecordController.java
app/backend/controllers/StatisticsController.java
app/frontend/src/administrative/reports/categories/examsReport.component.js
app/frontend/src/administrative/reports/categories/roomsReport.component.js
app/frontend/src/utility/file/file.service.ts

- also set json content type for self generated json files
- add some handling for non-base64 encoded file contents

CSCEXAM-232 set correct content types for self generated excels

---

app/backend/controllers/SettingsController.java
app/frontend/src/enrolment/enrolment.model.ts
app/frontend/src/enrolment/enrolment.service.ts
app/frontend/src/exam/editor/sections/section.template.html

- don't download instructions if not enrolling for regular exam
- check supported languages from db instead of config

CSCEXAM-234 Maturity instructions related fixes

---

app/backend/controllers/StudentExamController.java

- even though not a common use case, it is a common scenario for manual testing

CSCEXAM-256 examination when student is exam creator

---

app/backend/controllers/iop/transfer/impl/ExternalExamController.java
app/backend/models/sections/ExamSection.java
app/backend/models/sections/ExamSectionQuestion.java

- creator getting copied as-is from parent exam

CSCEXAM-266 fix copying of section questions

---

app/backend/controllers/ExamSectionController.java
app/frontend/src/exam/editor/sections/section.component.ts
conf/application.conf

- when adding exam questions
- also increase allowed max payload size

CSCEXAM-275 do not post redundant question data 

---

app/backend/controllers/ReviewController.java

- somehow ebean won't fetch stuff for us after 66 rows

CSCEXAM-223 Add additional fetch joins for review data

---

app/frontend/src/assets/languages/locale-fi.json

optional materials terminology changes (FIN)

CSCEXAM-117 optional materials localization (FIN)

---

app/backend/controllers/iop/collaboration/impl/CollaborativeExamController.java
app/backend/controllers/iop/collaboration/impl/CollaborativeExamSectionController.java
app/frontend/src/assets/languages/locale-en.json
app/frontend/src/assets/languages/locale-fi.json
app/frontend/src/assets/languages/locale-sv.json
app/frontend/src/exam/editor/publication/collaborativeExamOwnerSelector.template.html

- do not update direct exam properties on every update request
- e.g. section and question related updates do not need to update
anything exam related

CSCEXAM-293 collaborative exam, updates

---

app/backend/views/devindex.scala.html
app/backend/views/index.ejs
app/frontend/src/administrative/settings/settings.template.html
app/frontend/src/exam/editor/publication/autoEvaluation.template.html
app/frontend/src/exam/editor/sections/section.template.html
app/frontend/src/facility/schedule/startingTime.template.html
app/frontend/src/question/basequestion/essayForm.component.js
app/frontend/src/question/basequestion/questionBody.template.html
app/frontend/src/question/basequestion/weightedMultipleChoiceOptionForm.component.js
app/frontend/src/question/examquestion/examQuestion.template.html
app/frontend/src/review/assessment/grading/grading.template.html
app/frontend/src/review/assessment/maturity/grading.template.html
app/frontend/src/review/assessment/questions/clozeTest.template.html
app/frontend/src/review/assessment/questions/essayQuestion.template.html
app/frontend/src/review/assessment/questions/multiChoiceQuestion.template.html
app/frontend/src/review/questions/assessment/essayAnswer.template.html

- instead use it directly within numeric input elements
- avoids issues with google translate

CSCEXAM-337 remove language attribute from html element

---

app/frontend/src/assets/languages/locale-en.json
app/frontend/src/assets/languages/locale-fi.json
app/frontend/src/assets/languages/locale-sv.json
app/frontend/src/review/assessment/questions/clozeTest.component.js
app/frontend/src/review/assessment/questions/clozeTest.template.html
app/frontend/src/review/assessment/questions/essayQuestion.template.html
app/frontend/src/review/assessment/questions/multiChoiceQuestion.template.html

- also added missing translations
- limit decimal count to two also with essay scores

CSCEXAM-358 fixed decimal count for forced score related UI

---

app/frontend/src/examination/examination.component.js
app/frontend/src/examination/examination.service.js
app/frontend/src/examination/navigation/examinationToolbar.component.js

- do it regardless whether answer is empty or not

CSCEXAM-387 save all text answers when exam ends

---

app/backend/controllers/iop/collaboration/impl/CollaborativeExamController.java

Maybe not the most elegant solution, but I hesitate to have this implemented in @Authenticated annotation as it is used across the codebase and any restricting change there might brake functionality elsewhere.

CSCEXAM-385 clear some user data prior serialization

---

app/backend/impl/EmailComposerImpl.java

- in case no upcoming examinations for that exam

CSCEXAM-76 filter out some private exams from weekly report

---

app/backend/controllers/base/Index.scala
app/frontend/src/assets/languages/locale-en.json
app/frontend/src/assets/languages/locale-fi.json
app/frontend/src/assets/languages/locale-sv.json
app/frontend/src/reservation/admin/adminReservations.template.html
app/frontend/src/reservation/index.ts
app/frontend/src/reservation/reservation.controller.ts
app/frontend/src/reservation/reservationDetails.component.ts
build.sbt
project/plugins.sbt

- also upgrade Play Framework
- fix a Scala compilation warning

CSCEXAM-397 make a filter for displaying external reservations only

---

app/frontend/src/exam/editor/examTabs.component.ts
app/frontend/src/exam/editor/examTabs.template.html
app/frontend/src/exam/editor/sections/sectionQuestion.component.ts
app/frontend/src/question/basequestion/questionBody.component.js
app/frontend/src/review/listing/summary/examSummary.component.ts

- flow of server requests out of sync causing data version conflicts

CSCEXAM-415 Fix collaborative exam question attachment editing

---

app/backend/controllers/iop/transfer/impl/ExternalExamController.java
test/controllers/iop/ExternalExamControllerTest.java
test/resources/externalExamAttainment.json

- private exam, examination taken elsewhere
- end email to teachers when examination successfully taken
and results received in home organisation

CSCEXAM-430 Email about received external private examinations

---

app/backend/controllers/iop/transfer/impl/ExternalExamController.java
app/backend/impl/AutoEvaluationHandlerImpl.java
test/resources/externalExamAttainment.json

- also enhanded resolution of correct grade scale in this case

CSCEXAM-440 deliver course gradescale during transfer exam

---

app/frontend/src/assets/languages/locale-fi.json

Translation (FI) for Exam visit

CSCEXAM-239 Translations (FI)

---

app/backend/controllers/iop/collaboration/impl/CollaborationController.java
app/backend/controllers/iop/collaboration/impl/CollaborativeExamController.java
app/backend/controllers/iop/collaboration/impl/CollaborativeExamSectionController.java

- same as CSCEXAM-385 but in different place

CSCEXAM-452 clean user data when setting owner/modifier

---

app/backend/controllers/ReservationController.java
app/backend/controllers/iop/transfer/impl/ExternalExamController.java

- need the information once assessment comes back from remote end

CSCEXAM-410 provide trial count for enrolment

---

app/backend/controllers/ExamSectionController.java
app/backend/controllers/iop/collaboration/api/CollaborativeExamLoader.java
app/backend/controllers/iop/collaboration/impl/CollaborationController.java
app/backend/controllers/iop/collaboration/impl/CollaborativeAttachmentController.java
app/backend/controllers/iop/collaboration/impl/CollaborativeExamController.java
app/backend/controllers/iop/collaboration/impl/CollaborativeExamLoaderImpl.java
app/backend/controllers/iop/collaboration/impl/CollaborativeExamSectionController.java
app/frontend/src/exam/editor/sections/section.component.ts
app/frontend/src/exam/editor/sections/sectionQuestion.component.ts

- can not exceed question amount
- need to take that into account when removing questions

CSCEXAM-464 fix for updating lottery item count

---

app/frontend/package-lock.json
app/frontend/package.json
app/frontend/src/app.directive.ts
app/frontend/src/exam/editor/basic/basicExamInfo.template.html

- and use it on exam basic info tab

CSCEXAM-493 Add listener for CKEditor's blur event

---

app/backend/controllers/ExamSectionController.java
app/backend/models/sections/ExamSectionQuestion.java
app/frontend/src/assets/languages/locale-en.json
app/frontend/src/assets/languages/locale-fi.json
app/frontend/src/assets/languages/locale-sv.json
app/frontend/src/assets/styles/partial/_dashboard.scss
app/frontend/src/exam/editor/sections/sectionQuestion.component.ts
app/frontend/src/exam/editor/sections/sectionQuestion.template.html
app/frontend/src/exam/exam.model.ts
app/frontend/src/question/basequestion/claimChoiceForm.component.js
app/frontend/src/question/examquestion/examQuestion.component.js
app/frontend/src/question/examquestion/examQuestion.template.html
app/frontend/src/question/question.service.js
app/frontend/src/review/assessment/questions/claimChoiceAnswer.component.js
app/frontend/src/review/assessment/questions/claimChoiceAnswer.template.html

- Added claim choice question option editor to distributed editor view
- Claim choice option type is not determined by score for exam section question options instead of multiple choice option type (except for skip options since those won't ever change)
- Added missing error translation
- Other minor fixes

CSCEXAM-486: Distributed claim choice question fixes

---

app/backend/impl/CalendarHandlerImpl.java
app/frontend/src/assets/styles/main.scss
app/frontend/src/facility/machines/machineList.component.ts
app/frontend/src/facility/machines/machineList.template.html

- do not allow making reservations if ip address or name missing
- fix calculation of machine numbers in each state on UI

CSCEXAM-499 fixes for exam machine functionality

---

app/backend/controllers/iop/transfer/impl/ExternalCalendarController.java
app/frontend/src/calendar/calendar.template.html

CSCEXAM-516 Enable optional content selection for external exams

---

app/backend/controllers/ReviewController.java
app/frontend/src/app.directive.ts
app/frontend/src/review/assessment/grading/grading.component.js

- also improve teachers-list directive (template was confusing)

CSCEXAM-538 Allow exam inspector to override calculated scores

---

app/frontend/src/assets/languages/locale-en.json
app/frontend/src/assets/languages/locale-fi.json
app/frontend/src/assets/languages/locale-sv.json
app/frontend/src/exam/editor/basic/basicExamInfo.component.ts
app/frontend/src/exam/editor/basic/basicExamInfo.template.html
app/frontend/src/exam/editor/events/examinationEventDialog.component.ts

CSCEXAM-471 Removal of examination event

---

app/backend/controllers/CalendarController.java

- display current selection when starting to modify existing reservation

CSCEXAM-516 Optional sections with external reservation

---

app/frontend/src/assets/languages/locale-en.json

BYOD event language pack (eng)

BYOD event removal language pack (eng)

---

app/frontend/src/assets/languages/locale-sv.json

BYOD event removal language pack (swe-eng) tbchanged later

BYOD event removal language pack (swe-eng)

---

app/frontend/src/examination/question/examinationEssayQuestion.template.html
conf/seb.template.plist
test/functional/ByodConfigHandlerTest.java

- also disable file download/upload in SEB configuration

CSCEXAM-481 hide answer attachment controls from student

---

app/frontend/package-lock.json
app/frontend/package.json
app/frontend/src/assets/languages/locale-en.json
app/frontend/src/assets/languages/locale-fi.json
app/frontend/src/assets/languages/locale-sv.json
app/frontend/src/review/listing/summary/examSummary.component.ts
app/frontend/src/review/listing/summary/examSummary.template.html
app/frontend/src/review/review.module.js

- Switched from angular-chart.js lib to most recent ChartJS
- Recreated both charts on exam summary tab
- Removed line from grade time chart, changed color to red for better point visibility
- Fixed translations for grade time chart
- Minimum values set to 0 for both axes on grade time chart, max values will be defined by maximum score and duration of exam

CSCEXAM-562: Chart changes for grade time chart, switched angular-chart.js lib to chart.js

---

app/backend/util/excel/ExcelBuilder.java

- Allow duplicate questions from different sections to the report
- Refactored the code a bit

CSCEXAM-581: Question score report changes

---

app/backend/controllers/iop/collaboration/api/CollaborativeExamLoader.java
app/backend/controllers/iop/collaboration/impl/CollaborativeEnrolmentController.java
app/backend/controllers/iop/collaboration/impl/CollaborativeExamLoaderImpl.java
app/backend/controllers/iop/transfer/impl/ExternalExamController.java
app/backend/system/actors/CollaborativeAssessmentSenderActor.java
app/frontend/src/app.directive.ts

- answer attachment handling
- minor UI fixes

CSCEXAM-314 additional fixes

---

app/backend/controllers/iop/collaboration/impl/CollaborativeExamSectionController.java
app/frontend/package-lock.json
app/frontend/src/exam/editor/examTabs.component.ts
app/frontend/src/exam/editor/examTabs.template.html
app/frontend/src/exam/editor/sections/section.component.ts
app/frontend/src/exam/editor/sections/section.template.html
app/frontend/src/exam/editor/sections/sectionQuestion.component.ts
app/frontend/src/exam/editor/sections/sectionsList.component.ts
app/frontend/src/exam/editor/sections/sectionsList.template.html
app/frontend/src/question/selector/questionSelector.component.js

- Update questions on question editor without reloading whole exam from the backend (this prevents the strange scroll to bottom of the questions tab). Also set attachments for collaborative exams without reload.
- Fixed section question ordering (orderBy:sequenceNumber -> orderBy:'sequenceNumber')
- Question selector component now returns selected questions on successful close
- Some package-lock.json updates

CSCEXAM-596: Question editor fixes + package-lock.json changes

---

app/backend/controllers/SessionController.java
app/backend/controllers/base/BaseController.java
app/backend/controllers/integration/ReservationAPIController.java
app/backend/repository/EnrolmentRepository.java

- some random timing problem when resolving Ebean server during startup
- move EnrolmentRepository injection away from BaseController (not really needed there)
- use an injection provider for EbeanConfig and thus delay resolving EbeanServer
- hopefully this fixes the problems starting in prod mode (in some environments)

CSCEXAM-000 changes for DI wiring

---

app/frontend/src/review/listing/categories/graded.template.html
app/frontend/src/review/listing/categories/inLanguageInspection.template.html
app/frontend/src/review/listing/categories/inProgress.template.html
app/frontend/src/review/listing/categories/rejected.template.html
scripts/internal/create_assessments.py

- also fix an extra space character issue on assessment lists

CSCEXAM-598 add some variation to assessment creation script

---

app/frontend/src/reservation/reservation.controller.ts
app/frontend/src/reservation/reservationDetails.template.html

- regading home examination reservation view
- also hide the "permit retrial" button for such examinations

CSCEXAM-606 Fix display of participant name

---

app/frontend/src/assets/languages/locale-en.json
app/frontend/src/assets/languages/locale-fi.json
app/frontend/src/assets/languages/locale-sv.json
app/frontend/src/assets/styles/partial/_dashboard.scss
app/frontend/src/review/assessment/grading/toolbar.template.html

- Show disabled buttons as transparent instead of gray color
- Added popovers for grading buttons
- Translation changed for Lock the assessment -button

CSCEXAM-78: Grading buttons changes

---

app/backend/controllers/iop/collaboration/impl/CollaborativeExternalCalendarController.java
app/backend/controllers/iop/transfer/impl/ExternalCalendarController.java
app/backend/impl/CalendarHandler.java
app/backend/impl/CalendarHandlerImpl.java
app/frontend/src/utility/attachment/attachment.service.ts

- fix download of question attachments
- fix email notification sending

CSCEXAM-607 additional fixes for collaborative exam/external reservation

---

app/backend/controllers/ReservationController.java
app/frontend/src/app.directive.ts
app/frontend/src/reservation/reservationDetails.template.html

- Show deleted exams to admin users, hide from teachers
- Added some null checking to elements to avoid JS errors

CSCEXAM-608: Show deleted exams for admins + front end bug fixes

---

app/frontend/src/assets/styles/main.scss
app/frontend/src/assets/styles/partial/_dashboard.scss
app/frontend/src/assets/styles/partial/_defines.scss
app/frontend/src/assets/styles/partial/_exam.scss
app/frontend/src/assets/styles/partial/_library.scss
app/frontend/src/common/historyBack.component.js
app/frontend/src/common/historyBack.template.html
app/frontend/src/enrolment/active/activeEnrolment.template.html
app/frontend/src/enrolment/exams/examEnrolmentDetails.template.html
app/frontend/src/question/basequestion/claimChoiceForm.component.js
app/frontend/src/question/examquestion/examQuestion.template.html
app/frontend/src/review/assessment/grading/toolbar.template.html
app/frontend/src/review/assessment/maturity/toolbar.template.html

- Improved contrast of red color to reach WCAG level AA
- Improved keyboard accessibility for some components
- Added focus outline for enrolment menu
- Changed button colors

CSCEXAM-633: Accessibility improvements: improved red contrast, keyboard navigation and button colors

---

app/frontend/src/exam/editor/creation/newExam.template.html

CSCEXAM-644 Allow selecting examination type for all exams

---

app/backend/controllers/ExamController.java
app/backend/models/Exam.java
app/frontend/src/assets/styles/partial/_dashboard.scss
app/frontend/src/dashboard/teacher/categories/examListCategory.component.ts
app/frontend/src/dashboard/teacher/categories/examListCategory.template.html
app/frontend/src/exam/listing/examList.component.js
app/frontend/src/exam/listing/examList.template.html

- also some additional fixes to related admin UI

CSCEXAM-656 Selection of examination type when copying exam

---

app/backend/repository/EnrolmentRepository.java
app/frontend/src/enrolment/active/activeEnrolment.template.html

- there was a chance that they get displayed as mandatory sections in student's enrolment details UI

CSCEXAM-676 Fix display of non-selected sections

---

app/backend/impl/ExternalCourseHandlerImpl.java
conf/application.conf

- Also make language parameter optional

CSCEXAM-616 Possibility to use eppn for enrolment permission check

---

app/backend/system/SystemFilter.scala
app/backend/util/config/ByodConfigHandlerImpl.scala
app/backend/util/config/ConfigReader.java
app/backend/util/config/ConfigReaderImpl.java
conf/application.conf
conf/seb.template.plist
test/functional/ByodConfigHandlerTest.java

CSCEXAM-678 SEB configuration related fixes and improvements

Cscexam 678

---

app/backend/util/excel/ExcelBuilder.java

- adds hyperlinks to existing question header cells, so teachers can directly navigate to parent question

CSCEXAM-624: Question header cells will be hyperlinks to parent questions

---

app/backend/controllers/ReviewController.java
app/frontend/src/assets/languages/locale-en.json
app/frontend/src/assets/languages/locale-fi.json
app/frontend/src/assets/languages/locale-sv.json
app/frontend/src/review/listing/summary/examSummary.component.ts
app/frontend/src/review/listing/summary/examSummary.template.html

- show section averages and max scores by grouping exam sections by name
- only groups by current parent exam section names and counts in sections from child exams with matching names

CSCEXAM-623: Show section averages by grouping sections with name

---

app/backend/util/excel/ExcelBuilder.java

- show total scores for sections and exams
- also adds questions and sections that got deleted/renamed, if those existed on child exams
- changed the way score columns will be rendered to excel
- created few helper methods for repeated functionality

CSCEXAM-536: Print question report with section totals

---

app/backend/controllers/BaseAttachmentInterface.java
app/backend/controllers/iop/transfer/impl/DataTransferController.java
app/backend/system/AuditLogger.java
test/controllers/iop/DataTransferControllerTest.java

- Check attachments' combined file size when exporting. It may not exceed a preconfigured limit
- Disable logging for data import requests

CSCEXAM-682 Question transfer improvements

---

ui/src/app/examination/question/examinationEssayQuestion.component.html
ui/src/app/review/listing/categories/archived.component.html
ui/src/app/review/listing/categories/graded.component.html
ui/src/app/review/listing/categories/gradedLogged.component.html
ui/src/app/review/listing/categories/inLanguageInspection.component.html
ui/src/app/review/listing/categories/inProgress.component.html
ui/src/app/review/listing/categories/rejected.component.html
ui/src/app/review/listing/reviewList.component.html
ui/src/app/review/listing/summary/examSummary.component.html
ui/src/app/review/listing/summary/examSummary.component.ts
ui/src/app/review/questions/listing/questionReview.component.html
ui/src/app/review/questions/listing/questionReviews.component.html

- fixed styles to review components, exam summry and question review tabs
- fixed duration parsing on exam summary page

Exam summary and style fixes

---

public/assets/i18n/fi.json

Finnish language package change for EXAM 6.0

CSCEXAM-661 Finnish language package change for EXAM 6.0

---

public/assets/i18n/en.json

English language package changes for EXAM 6.0

CSCEXAM-661 English language package changes for EXAM 6.0

---

public/assets/i18n/sv.json

Swedish language package changes for EXAM 6.0

CSCEXAM-661 Swedish language package changes for EXAM 6.0

---

app/controllers/SessionController.java
test/base/IntegrationTestCase.java
test/resources/courseUnitInfo3.json

CSCEXAM-805 Changes to student id format and parsing

Cscexam 805

---

ui/src/app/enrolment/waiting-room/waitingRoom.component.html
ui/src/app/examination/question/examinationEssayQuestion.component.html
ui/src/app/maturity/listing/reviewedInspections.component.html

- fix DST adjustment in waiting room for SEB/home examinations
- hide answer attachment adding with SEB/home examinations
- fix some search issues with finalized language inspections

CSCEXAM-000 minor fixes

---

ui/src/app/examination/examination.component.ts
ui/src/app/examination/logout/examinationLogout.component.ts
ui/src/app/session/session.service.ts

- Causes unwanted UI state transfers after examination's ending

CSCEXAM-730 Disable session checks for duration of examination

---

ui/src/app/reservation/reservationDetails.component.html

- complex logic for different types of reservations

CSCEXAM-824 Fix problem with displaying emails in admin review UI

---

app/impl/EmailComposerImpl.java
app/system/SystemInitializer.java

- Add exeption to error report
- Check against missing course in weekly report

CSCEXAM-705 Fix weekly email missing timezone

---

ui/src/app/calendar/helpers/slotPicker.component.ts

Disables popover if room in the list is available. Fixes a bug where popover component is stuck in the corner of the screen with wrong information, only reproduced in Firefox.

CSCEXAM-854 Add outOfServiceGate to slotPicker component

---

app/util/csv/CsvBuilder.java
app/util/csv/CsvBuilderImpl.java

CSCEXAM-826 Add CSV delimiter detector

---

ui/src/app/examination/examination.service.ts

- parallel execution does not suit

CSCEXAM-863 Run autosaver in order to avoid version conflicts

---

ui/src/app/assets/styles/partial/_dashboard.scss
ui/src/app/assets/styles/partial/_defines.scss
ui/src/app/calendar/helpers/selectedRoom.component.ts
ui/src/app/calendar/helpers/slotPicker.component.ts

Fix exam room title/location display overlap issues

CSCEXAM-857 Fix droplist name slicing and width issues

---

ui/src/app/question/library/search/librarySearch.component.html
ui/src/app/question/library/search/librarySearch.component.ts

Adding subscribe to list menu updates it when the data has been fetched.

CSCEXAM-866 Add subscribe to exam listMenu

---

app/controllers/ExaminationController.java
app/controllers/iop/transfer/impl/ExternalExaminationController.java
app/models/Exam.java
app/repository/EnrolmentRepository.java
app/repository/ExaminationRepository.java
conf/routes
test/controllers/ExaminationControllerTest.java
ui/package-lock.json
ui/src/app/app-routing.module.ts
ui/src/app/enrolment/waiting-room/waitingRoom.component.ts
ui/src/app/interceptors/httpExaminationInterceptor.ts

- create student's copy already when waiting for exam to start
- this should ease the db access load when mass examinations start thus eliminating a known performance bottleneck.

CSCEXAM-592 Refactor examination starting logic

---

public/assets/i18n/en.json
public/assets/i18n/fi.json
public/assets/i18n/sv.json
ui/src/app/enrolment/exams/examEnrolmentDetails.component.html
ui/src/app/enrolment/exams/examEnrolmentDetails.component.ts

CSCEXAM-675 Add more informative texts

---

public/assets/i18n/en.json
public/assets/i18n/fi.json
public/assets/i18n/sv.json

At some point at merging there was one comma left out from a row.

CSCEXAM-675 Fix formatting in i18n file

---

public/assets/i18n/en.json
public/assets/i18n/fi.json
public/assets/i18n/sv.json
ui/src/app/assets/styles/partial/_defines.scss
ui/src/app/assets/styles/partial/_student_exam.scss
ui/src/app/assets/styles/partial/_vmenu.scss
ui/src/app/calendar/calendar.component.html
ui/src/app/calendar/helpers/slotPicker.component.ts
ui/src/app/enrolment/active/activeEnrolment.component.html
ui/src/app/enrolment/active/helpers/activeEnrolmentMenu.component.html
ui/src/app/enrolment/finished/examParticipations.component.html
ui/src/app/exam/editor/basic/softwareSelector.component.html
ui/src/app/examination/clock/examinationClock.component.html
ui/src/app/examination/header/examinationHeader.component.html
ui/src/app/examination/navigation/examinationNavigation.component.html
ui/src/app/examination/navigation/examinationToolbar.component.html
ui/src/app/examination/question/examinationEssayQuestion.component.html
ui/src/app/navigation/navigation.component.html
ui/src/app/navigation/navigation.component.ts

Add skip to content button to main menu
Fix exam room selection to be accessible with keyboard
Fix buttons so that they use <button> element rather than key event handler

CSCEXAM-874: Accessibility Improvements

---

ui/src/app/enrolment/waiting-room/waitingRoom.component.html
ui/src/app/review/listing/dialogs/abortedExams.component.html

- also fix template errors with waiting room component

CSCEXAM-939 Fix retrial permitting (merging error)

---

ui/src/app/review/listing/summary/examSummary.component.html
ui/src/app/review/listing/summary/examSummary.component.ts

- seems it is not doable with strict typing :(
- might be something wrong with the provided types not reflecting real data

CSCEXAM-000 Fix percentage calculation for exam summary pie chart

---

app/controllers/ExaminationController.java
app/controllers/ReservationController.java
app/models/sections/ExamSection.java
app/repository/ExaminationRepository.java
ui/src/app/enrolment/search/collaborativeExamSearch.component.html
ui/src/app/reservation/reservation.service.ts

- also some prettier-fixes (need to run manually for java files because of a bug with lint-staged library)

CSCEXAM-926 Fix query of examination event no-shows

---

ui/src/app/app.component.ts
ui/src/app/exam/editor/basic/basic-exam-info.component.html
ui/src/app/exam/editor/basic/exam-inspector-picker.component.html
ui/src/app/exam/editor/basic/exam-owner-picker.component.html
ui/src/app/exam/editor/basic/software-picker.component.ts
ui/src/app/exam/editor/events/examination-event-dialog.component.html
ui/src/app/exam/editor/publication/collaborative-exam-owner-picker.component.ts
ui/src/app/exam/editor/publication/exam-participant-picker.component.ts
ui/src/app/exam/editor/publication/exam-pre-participant-picker.component.ts
ui/src/app/exam/editor/publication/exam-publication.component.html
ui/src/app/exam/editor/publication/exam-publication.component.ts
ui/src/app/exam/editor/sections/exam-material-picker.component.html
ui/src/app/question/basequestion/question-body.component.html
ui/src/app/question/library/export/library-transfer.component.html
ui/src/app/question/library/owners/library-owners.component.ts
ui/src/app/question/tags/tag-picker.component.ts
ui/src/app/session/session.service.ts
ui/src/app/shared/date/date-picker.component.html
ui/src/assets/styles/partial/_dashboard.scss
ui/src/assets/styles/partial/_defines.scss

- also fixes race condition with translation service while logging in

CSCEXAM-966 Fix found style issues

---

ui/src/app/facility/rooms/room-mass-edit.component.ts
ui/src/app/facility/rooms/room.service.ts
ui/src/app/facility/rooms/rooms.component.html
ui/src/app/facility/schedule/exception-dialog.component.html
ui/src/app/facility/schedule/exception-dialog.component.ts
ui/src/app/facility/schedule/exceptions.component.ts
ui/src/assets/i18n/en.json
ui/src/assets/i18n/fi.json
ui/src/assets/i18n/sv.json

CSCEXAM-1038 Add extra opening hours options to exception working hours

---

ui/src/app/exam/editor/assessment/exam-feedback-config.component.html
ui/src/app/exam/editor/assessment/exam-feedback-config.component.ts

- in case graded and logged assessments exist

CSCEXAM-996 Disallow turning feedback config on/off

---

ui/src/app/exam/editor/publication/exam-publication.component.html
ui/src/app/review/questions/listing/question-reviews.component.ts

- also fix a tab highlighting issue

CSCEXAM-1006 Remove obsolete subheader from exam publication tab

---

app/system/App.java
app/system/SystemInitializer.java
app/system/actors/ExternalExamExpirationActor.java
test/controllers/CalendarControllerTest.java

- after fixed period passed after successful examination

CSCEXAM-1054 Clearing of external exam answers

---

ui/src/app/reservation/reservation-base.component.ts
ui/src/app/reservation/reservation-details.component.html

- there appears to be cases when incoming external reservation has no external user reference
- don't know how that can be, might be just problems with test data but will have to keep eye on these
- there were like 25 such cases from as early as 2019 in dataset so these are pretty rare and it's not a new problem it seems

CSCEXAM-1061-5 Fix handling of unidentified reservations on UI

---

ui/src/app/exam/editor/events/examination-event-search.component.html
ui/src/app/exam/editor/events/examination-event-search.component.ts
ui/src/assets/styles/partial/_defines.scss

CSCEXAM-961 Fix examination-event-search initial search

---

app/impl/ExamUpdaterImpl.java
ui/src/app/dashboard/staff/teacher/categories/exam-list-category.component.ts

- if enrolments to future examination events exist

CSCEXAM-1077 Disallow exam removal

---

app/impl/NoShowHandlerImpl.java
app/models/Reservation.java
app/system/actors/ReservationPollerActor.java
conf/evolutions/default/129.sql

CSCEXAM-1107 Remodel no-show logic for external reservations

---

app/controllers/ExamAnswerController.java
app/models/Exam.java
conf/evolutions/default/130.sql
ui/src/app/enrolment/finished/exam-feedback.component.html
ui/src/app/enrolment/finished/exam-participation.component.html
ui/src/app/exam/editor/assessment/exam-feedback-config.component.css
ui/src/app/exam/editor/assessment/exam-feedback-config.component.html
ui/src/app/exam/editor/assessment/exam-feedback-config.component.ts
ui/src/assets/i18n/en.json
ui/src/assets/i18n/fi.json
ui/src/assets/i18n/sv.json
ui/src/assets/styles/partial/_dashboard.scss

- also fixed some style issues

CSCEXAM-1127 Another update to feedback release logic

---

app/controllers/ExamAnswerController.java
app/controllers/ReviewController.java
app/models/questions/ClozeTestAnswer.java
ui/src/assets/styles/partial/_exam.scss

- i.e. hide info about answer being correct or incorrect

CSCEXAM-1001 Mark cloze test answers as neutral

---

ui/src/app/reservation/reservation-base.component.ts

CSCEXAM-1088 Do not fetch BYOD exams if room or machine id present

---

ui/src/app/exam/exam.model.ts
ui/src/app/reservation/reservation-base.component.ts

- applies to reservation search

CSCEXAM-1164 Fix using collaborative exam name as search param

---

ui/src/app/interceptors/error-interceptor.ts
ui/src/app/session/session.service.ts

- Fix detection of network connectivity error
- Fix redirection in case there are query parameters present when logging in

CSCEXAM-1196 Fix redirection from HAKA with query params 

---

app/repository/EnrolmentRepository.java
ui/src/app/dashboard/student/student-dashboard.service.ts
ui/src/app/enrolment/active/active-enrolment.component.html
ui/src/app/enrolment/active/active-enrolment.component.ts
ui/src/app/enrolment/wrong-location/wrong-location.service.ts
ui/src/app/interceptors/error-interceptor.ts
ui/src/app/session/session.service.ts

Couple of other things
- Also handle errors that we can't display more gracefully
- Clean session storage after user logged out

CSCEXAM-426 Time zone handling improvements

---

ui/src/app/examination/examination.component.html
ui/src/app/examination/examination.component.ts
ui/src/app/examination/navigation/examination-toolbar.component.html
ui/src/app/examination/section/examination-section.component.ts

This do not affect the visual structure of the page.

CSCEXAM-1254 Change examination view structure to make sense for screen reader

---

app/controllers/SessionController.java
app/controllers/iop/transfer/impl/ExternalExamController.java

- add some logging for failed login attempts

CSCEXAM-1241 Check pre-enrolments for all users (including existing)

---

ui/src/app/administrative/users/users.component.html
ui/src/app/enrolment/waiting-room/waiting-room.component.html
ui/src/app/enrolment/waiting-room/waiting-room.component.scss
ui/src/app/enrolment/waiting-room/waiting-room.component.ts
ui/src/app/review/assessment/assessment.component.html
ui/src/app/review/assessment/assessment.service.ts
ui/src/app/review/assessment/collaborative-assessment.service.ts
ui/src/app/review/assessment/grading/grading.component.html
ui/src/app/review/listing/review-list.component.html
ui/src/app/review/listing/speed-review.component.html

CSCEXAM-1294 Fix rerouting to review list from collab exam assessment

---

app/controllers/SessionController.java
app/util/config/ConfigReader.java
app/util/config/ConfigReaderImpl.java
test/base/IntegrationTestCase.java
test/controllers/SessionControllerTest.java

- Supported languages are those for which we have translations

CSCEXAM-1304 Do not set new user's language to unsupported one

---

ui/src/app/enrolment/active/helpers/active-enrolment-menu.component.html
ui/src/app/enrolment/waiting-room/waiting-room.component.ts
ui/src/app/examination/clock/examination-clock.component.ts

- fix unsubscribing from examination clock
- allow negative numbers for waiting-room delay clock

CSCEXAM-1294 Fix active enrolment menu condition

---

package.json
test/controllers/CalendarControllerTest.java
test/controllers/EnrolmentControllerTest.java
test/controllers/EnrolmentInterfaceTest.java
test/controllers/ExamControllerTest.java
test/controllers/ExaminationControllerTest.java
test/controllers/QuestionControllerTest.java
test/controllers/StudentActionControllerTest.java
test/controllers/integration/ExamAPIControllerTest.java
test/controllers/integration/ExternalCourseHandlerTest.java
test/controllers/iop/BaseCollaborativeAttachmentControllerTest.java
test/controllers/iop/DataTransferControllerTest.java
test/controllers/iop/ExternalCalendarInterfaceTest.java
test/controllers/iop/ExternalExamControllerTest.java
test/controllers/iop/ExternalExaminationControllerTest.java
test/functional/ByodConfigHandlerTest.java
test/functional/MoodleImporterTest.java
test/helpers/AttachmentServlet.java
test/helpers/RemoteServerHelper.java
ui/src/app/enrolment/finished/exam-feedback.component.html

- make java formatting applicable for tests also
- fix weird rounding bug in calendar controller tests

CSCEXAM-1301 Show question answers also for archived assessments

---

ui/src/app/enrolment/finished/exam-participations.component.html
ui/src/app/navigation/navigation.component.html
ui/src/assets/i18n/en.json
ui/src/assets/i18n/fi.json
ui/src/assets/i18n/sv.json

Add aria-current to navigation

CSCEXAM-1242 Remove autofocus from search field

---

app/impl/EmailComposerImpl.java
ui/src/app/exam/editor/creation/course-selection.component.html

- Email about being added as parcipant to a BYOD exam

 CSCEXAM-1203 Fix date formatting

---

ui/src/app/exam/editor/events/examination-event-dialog.component.html
ui/src/app/exam/editor/events/examination-event-dialog.component.ts

- show conflicting event times (not just dates)
- do not filter out other events of the exam in question

CSCEXAM-1258 Event capacity modifications

---

app/controllers/enrolment/ReservationController.java
conf/routes
ui/src/app/reservation/admin/change-machine-dialog.component.ts
ui/src/app/reservation/reservation.service.ts
ui/src/app/shared/select/dropdown-select.component.ts

- also fix layout issue with dropdown-select component
- add some more functionality to dropdown-select component
- modernize some code in ReservationController

CSCEXAM-105 Allow admin to change reservation's room

---

app/system/actors/ExamAutoSaverActor.scala
ui/src/app/calendar/calendar.component.ts

- also get rid of one useless error note on UI when canceling an external reservation

CSCEXAM-1379 Fix exam auto-saving problem

---

app/controllers/user/SessionController.java
app/security/AuthorizationHandler.java
app/security/scala/Auth.scala
ui/src/app/review/assessment/grading/grading.component.html
ui/src/app/review/assessment/maturity/grading.component.html
ui/src/app/review/assessment/maturity/grading.component.ts

- Support for multiple permissions in session & auth

CSCEXAM-1267 Assessment info also for maturity exams
